### ISSUE TITLE
Box name as uuid

### ISSUE THREAD

**Issue by lane-c-wagner** [Q-Vault/qvault#136]
We only want each user to have one of each box type, with the exception that you can have as many custom boxes as you want. Custom boxes can be created as "Custom Box 1, Custom Box 2...etc"

The box name should be editable but can't be saved if it conflicts with an existing box. On the add box screen the box types should be disabled for the boxes that already exist.

Custom boxes should just be full of name-value pairs.

**Comment by preston-wagner** [comment]
https://github.com/Q-Vault/qvault/pull/147
