### ISSUE TITLE
New error message style (figma)

### ISSUE THREAD

**Issue by lane-c-wagner** [Q-Vault/qvault#139]
https://www.figma.com/file/FuZ4AXSLHo471rgo7SZDX8hc/Qvault-App?node-id=0%3A2157

**Comment by preston-wagner** [comment]
Is the arrow part crucial?

**Comment by lane-c-wagner** [comment]
We can worry about it later. This is fine for MVP, those mocks will always be there. I updated the PR, wiating for you final apporval. https://github.com/Q-Vault/qvault/pull/148

**Comment by preston-wagner** [comment]
https://github.com/Q-Vault/qvault/pull/148
