### ISSUE TITLE
Dropdown delete box button (figma)

### ISSUE THREAD

**Issue by lane-c-wagner** [Q-Vault/qvault#142]
https://www.figma.com/file/FuZ4AXSLHo471rgo7SZDX8hc/Qvault-App?node-id=0%3A82

**Comment by lane-c-wagner** [comment]
We finished the "delete secret" feature, but we still need a dropdown for the box that just has a "delete box" options. The hotdog menu probably just goes next to the "plus" icon for adding secrets.

**Comment by lane-c-wagner** [comment]
I'll handle this one

**Comment by preston-wagner** [comment]
Thanks!
