### ISSUE TITLE
Success checkmark in field on success instead of alert (figma comment)

### ISSUE THREAD

**Issue by lane-c-wagner** [Q-Vault/qvault#143]
Instead of alerting on things like "registered email successfully" we should show a checkmark in the field and move on.

**Comment by preston-wagner** [comment]
Are we talking about _all_ alerts, or just some specific ones?

**Comment by lane-c-wagner** [comment]
Just all the applicable ones. We do need to get all alerts out eventually
though

**Comment by preston-wagner** [comment]
I mean, which ones are "applicable"? Any that are "success" alerts?

**Comment by lane-c-wagner** [comment]
Probably any involving a form for now

**Comment by lane-c-wagner** [comment]
Password changed, cloud vault created, etc.
