### ISSUE TITLE
Remove "simple-keyboard" dependency

### ISSUE THREAD

**Issue by lane-c-wagner** [Q-Vault/qvault#227]
We should copy the code we use from the simple-keyboard module into our repo. This is a potential attack vector down the road through npm. If we need to update for some reason down the line we will do so manually.

**Comment by preston-wagner** [comment]
https://github.com/Q-Vault/qvault/pull/251

**Comment by lane-c-wagner** [comment]
Seeing as simple-keyboard has no dependencies, can we pull this one into locked_dependencies as well? Or did you run into trouble?

**Comment by preston-wagner** [comment]
https://github.com/Q-Vault/qvault/pull/253
