### ISSUE TITLE
Problems with box_types.es6 and secret formating

### ISSUE THREAD

**Issue by lane-c-wagner** [Q-Vault/qvault#297]
We have some tech debt in box_types.es6 that will make modifying names and adding functionality difficult.

Currently we are keying off of display names, which is bad for the obvious reason that we can't change them. The "fields" array should probably be an object of objects. For example:

````
fields: {
    wallet_name:{
        displayName: "Wallet Name",
        type: String,
        ...
    },
    ....
}
````

The entire object should follow a similar pattern:

```
export default {
    cryptocurrency:{
        displayName: "Cryptocurrency",
        ...
    },
    .....
}
```

Then we will be able to more reliably key into the object and change display names.

We also have a problem where I potentially want to add non-visible data to the secrets stored in a vault. Currently a secret's top level keys are its fields. For example:

```
v-model=secret["field.name"]
```

I would like the secret to be structured like this:

```
secret = {
    fields: {
        wallet_name: "foo",
        ticker: "BAR",
    },
    // then in the future we can add "data" or something here
}
```

The bigger challenge here of course is backwards compatibility. I would recommend we have a function that reads the old format, and converts it to the new format (probably in "lib") with some unit tests. Then, when opening a vault we check the version number and run it through the converter if it is an old vault.

**Comment by preston-wagner** [comment]
Hmm. The annoying thing about this is that we lose the ordering a list provides. Why not just add an optional `display_name` if we want to change the names in `box_types.js`? I'm cool with restructuring the secrets themselves, though.

**Comment by lane-c-wagner** [comment]
Good point, let's keep it an array then. Let's just add a displayName and a key field. Name can probably go away. We should also camelCase everything and of course make a mapping for reverse compatibility.
