### ISSUE TITLE
Save "preferences" file locally with offline mode as first preference

### ISSUE THREAD

**Issue by lane-c-wagner** [Q-Vault/qvault#353]
In the same location as the "last_used_vault" file, we should store a "preferences.json" file. This file should have a package in the ".lib" folder that handles interactions with it. For the purposes of this issue, it will be a simple json object written to a file:

```
{
  "onlineMode": true
}
```

When the app starts, it should read this file and set onlineMode accordingly. Each time "onlineMode" is changes, it should be written to the file.

**Comment by elenamik** [comment]
I would like to try and tackle this one.
