### ISSUE TITLE
Figure out how to enable contextIsolation without breaking app

### ISSUE THREAD

**Issue by lane-c-wagner** [Q-Vault/qvault#57]
https://electronjs.org/docs/tutorial/security#3-enable-context-isolation-for-remote-content

In main.js:

// Create the browser window.
  mainWindow = new BrowserWindow({
    webPreferences:{
      nodeIntegration: false,
      contextIsolation: false, // We need to figure out how to enable this
      preload: path.join(__dirname, 'preload.js')
    },
    backgroundColor: '#131617',
    x: mainWindowState.x,
    y: mainWindowState.y,
    width: mainWindowState.width,
    height: mainWindowState.height,
    icon: 'src/img/qvault-icon.png', 
    show: false 
  });
  mainWindowState.manage(mainWindow);

**Comment by preston-wagner** [comment]
Why do we want this? We aren't loading any remote or untrusted scripts, are we?

**Comment by lane-c-wagner** [comment]
This is low priority. Just a nice to have. I was thinking cross site
scripting or something

**Comment by lane-c-wagner** [comment]
Closed for now, probably unnecessary at least until it becomes non-experimental.
