### ISSUE TITLE
vue-svg-loader breaking svgs

### ISSUE THREAD

**Issue by lane-c-wagner** [Q-Vault/qvault#77]
The svgs in the "add-box" screen are blank since adding vue-svg-loader. I tested to make sure they worked if loaded manually. We either need to figure out whats going on, or not use the loader.

**Comment by preston-wagner** [comment]
hmm... svgs are annoying because you can only style them with css if you embed them in the page, but you can't (as far as I can tell) have separate loaders for embeded and non-embeded svgs. I might just turn the embedded ones into .vue files to save the hassle.

**Comment by lane-c-wagner** [comment]
Works for me

**Comment by lane-c-wagner** [comment]
fixed
